### ISSUE TITLE
A lot of inconsistent argument use of "database  name"

### ISSUE THREAD

**Issue by chrisduong** [sensu-plugins/sensu-plugins-postgres#15]
Hi,

In `check-postgres-alive`, it is **database** argument.

```
  option :database,
         description: 'Database schema to connect to',
         short: '-d DATABASE',
         long: '--database DATABASE',
         default: 'test'
```

But in other checks, such as `metric-postgres-locks`, it is **db**, while the **con** object is still calling _config[:database]_, so the check would **fail**, as _config[:database] is **nil**.

```
  con     = PG.connect(host: config[:hostname],
                         dbname: config[:database],
                         user: config[:user],
                         password: config[:password],
                         connect_timeout: config[:timeout])
```

I've spotted a lot of this problem in other checks as well, I'm willing to make a pull request if we agree to use **database** as the argument name for _dbname_ throughout the repo.

**Comment by majormoses** [comment]
closed per https://github.com/sensu-plugins/sensu-plugins-postgres/issues/18
