### ISSUE TITLE
bonsai.sensu.io does not provide a build for Ubuntu (any release)

### ISSUE THREAD

**Issue by AndreasUfert** [sensu-plugins/sensu-plugins-postgres#153]
Hi,

after adding this asset to a Sensu Go backend, no usable build for Ubuntu (LTS) based agents can be found resulting in "entity not filtered, not installing asset build" in the sensu-agent's log when any check is about to run.

Regards, nak

**Comment by AndreasUfert** [comment]
I guess this PR will solve this? https://github.com/sensu-plugins/sensu-plugins-postgres/pull/157

**Comment by lrosenman** [comment]
They've merged that PR (#157), but haven't rebuilt it yet on Bonsai.  

Who do we have to ask nicely to build it?

**Comment by AndreasUfert** [comment]
Fixed with Version 4.3.0
