### ISSUE TITLE
check-postgres-connections does not work with 9.6

### ISSUE THREAD

**Issue by chrisferry** [sensu-plugins/sensu-plugins-postgres#21]
In 9.6 they've replaced the waiting column in pg_stat_activity with 2 columns wait_event and wait_event_type

Check failed to run: ERROR: column "waiting" does not exist
LINE 1: select count(*), waiting from pg_stat_activity where datname...
^
, ["/var/lib/gems/2.2.0/gems/sensu-plugins-postgres-0.1.1/bin/metric-postgres-connections.rb:83:in `exec'", "/var/lib/gems/2.2.0/gems/sensu-plugins-postgres-0.1.1/bin/metric-postgres-connections.rb:83:in `run'", "/var/lib/gems/2.2.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]

**Comment by eheydrick** [comment]
Fixed with https://github.com/sensu-plugins/sensu-plugins-postgres/pull/22 and released in [1.0.0](https://rubygems.org/gems/sensu-plugins-postgres/versions/1.0.0).
