### ISSUE TITLE
Mismatch of parameter names for "count_tuples" option.

### ISSUE THREAD

**Issue by wilson496** [sensu-plugins/sensu-plugins-postgres#23]
The count_tuples option for this script is never checked. However, there is a check for an option named "check_tuples", which is never initialized. 

This makes the script fail, since rather than checking the number of tuples it, it will attempt to grab the first tuple of an empty PG::Result list. 

Any assistance is appreciated.

**Comment by eheydrick** [comment]
Whoops, that is an oversight. I pushed a fix in 32d71ed37315e33c01368054789829b45015ac19 and will release it in a new version shortly.

**Comment by eheydrick** [comment]
Fix is in 1.0.1, now live on rubygems. Thanks for submitting the issue!
