### ISSUE TITLE
bug count of metric-postgres-locks.rb 

### ISSUE THREAD

**Issue by madboxkr** [sensu-plugins/sensu-plugins-postgres#26]
https://github.com/madboxkr/sensu-plugins-postgres/pull/1/files
Please see this changement
A count is never returned correct values on monitoring after use "group by" on request.
Please fix this issue on your code.

**Comment by eheydrick** [comment]
Hi @madboxkr, thanks for noticing the issue and coming up with a fix. Could you open a PR in this repo and we'll get your fix in.

**Comment by majormoses** [comment]
it looks like that branch just needs to be rebased against upstream and create a pr. If someone else wants to take this it should be fairly trivial to do this.

**Comment by majormoses** [comment]
I pulled the patch into #39

**Comment by eheydrick** [comment]
Released in 1.4.2: https://rubygems.org/gems/sensu-plugins-postgres/versions/1.4.2

**Comment by eheydrick** [comment]
Thanks for the fix @madboxkr and @majormoses for getting it in!
