### ISSUE TITLE
Postgres 10 support: `ERROR: function pg_current_xlog_location() does not exist`

### ISSUE THREAD

**Issue by opusmagnum** [sensu-plugins/sensu-plugins-postgres#40]
After PostgreSQL upgrade to version 10.0 I got the following error:
```
Check failed to run: ERROR: function pg_current_xlog_location() does not exist LINE 1: SELECT pg_current_xlog_location() ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. , ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-postgres-1.4.2/bin/check-postgres-replication.rb:120:in `exec'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-postgres-1.4.2/bin/check-postgres-replication.rb:120:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"
```

The reason for is -- functions `pg_current_xlog_location` is renamed to `pg_current_wal_lsn`. More about new function names -- https://wiki.postgresql.org/wiki/New_in_postgres_10#Renaming_of_.22xlog.22_to_.22wal.22_Globally_.28and_location.2Flsn.29
My workaround for now would be:
```
CREATE FUNCTION pg_catalog.pg_current_xlog_location() RETURNS pg_lsn AS $$
BEGIN
    RETURN pg_current_wal_lsn();
END;
$$ LANGUAGE plpgsql;
CREATE FUNCTION pg_catalog.pg_last_xlog_receive_location() RETURNS pg_lsn AS $$
BEGIN
    RETURN pg_last_wal_receive_lsn();
END;
$$ LANGUAGE plpgsql;
```

Did anybody find a better solution for it?

**Comment by majormoses** [comment]
Thanks for reporting! I can think of two paths forward:
- detect version and conditionally make the request
- attempt new function and fallback to old function


This could be parsed to pull out the major version for a conditional check to issue the appropriate command:
```
postgres=# SELECT version();
--------------------------------------------------------------------------------------------------
 PostgreSQL 10.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit
(1 row)
```


Alternatively we attempt calling new function and rescue to older as fallback:
```ruby
begin
  master = conn_master.exec('SELECT pg_current_wal_lsn()').getvalue(0, 0)
rescue
  master = conn_master.exec('SELECT pg_current_xlog_location()').getvalue(0, 0)
end

**Comment by phumpal** [comment]
I was bit by this a few weeks ago after upgrading to PostgreSQL 10.

@majormoses I've submit a PR as a potential fix. It will need to be rebased but the second commit is more idiomatic Ruby. PTAL.

**Comment by majormoses** [comment]
@phumpal thanks for picking this up I have left some comments.

**Comment by phumpal** [comment]
@opusmagnum try the [1.4.3](https://rubygems.org/gems/sensu-plugins-postgres/versions/1.4.3) release?

**Comment by opusmagnum** [comment]
Thank you for the fix, I will try the new version in the next days and let you know.

**Comment by edevreede** [comment]
I think this change breaks on PostgreSQL 9. It gives the following error on my Debian 9 install which has 9.6.4-0+deb9u1 installed. When I revert the change the plugin works fine!

```
# sudo -u sensu /opt/sensu/embedded/bin/check-postgres-replication.rb  --master-host 172.17.0.2 --slave-host 172.17.0.3
Check failed to run: ERROR:  function pg_current_wal_lsn() does not exist
LINE 1: SELECT pg_current_wal_lsn()
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
, ["/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-1.4.3/bin/check-postgres-replication.rb:128:in `exec'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-1.4.3/bin/check-postgres-replication.rb:128:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```

```
# sudo -u sensu /opt/sensu/embedded/bin/check-postgres-replication.rb  --master-host 172.17.0.2 --slave-host 172.17.0.3
CheckPostgresReplicationStatus OK: replication delayed by 0.0MB :: master:0/3000AE0 slave:0/3000AE0 m_segbytes:16777216
```

**Comment by majormoses** [comment]
Hmm I will try to replicate this today or tomorrow.

**Comment by majormoses** [comment]
Ya looking at the code there is definitely something wrong there, its 3 AM and I don't think I am gonna find whats wrong. Maybe after some sleep I will be able to spot what is wrong. For now I am gonna yank it from rubygems to prevent anyone from downloading that version anymore.

**Comment by majormoses** [comment]
https://rubygems.org/gems/sensu-plugins-postgres
![image](https://user-images.githubusercontent.com/3145127/32545712-6de6f1c6-c431-11e7-944e-272d2a157e48.png)
https://rubygems.org/gems/sensu-plugins-postgres/versions/1.4.3
![image](https://user-images.githubusercontent.com/3145127/32545681-593ece56-c431-11e7-80f9-871c4bd4f9c3.png)

**Comment by majormoses** [comment]
This is why we need real integration tests.

**Comment by phumpal** [comment]
> This is why we need real integration tests.

Agreed and completely my fault.

My 9.6.5 instances were already terminated before I pushed https://github.com/sensu-plugins/sensu-plugins-postgres/pull/41/commits/7fcf024f5bea6c45438a54171a3312236d3878da so I wasn't able to test.

> I think this change breaks on PostgreSQL 9

Yep, trivial change and something I should've caught.

PR forthcoming.

**Comment by majormoses** [comment]
@phumpal any chance you'd be willing to write some integration tests if I stand up the skeleton with `test-kitchen`, `kitchen-docker`, and `servespec`? If you want an example you can take a look at https://github.com/sensu-plugins/sensu-plugins-dcos.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-postgres/versions/1.4.4

**Comment by phumpal** [comment]
@edevreede @opusmagnum mind testing 1.4.4 w/your pg 9.x versions?

>  any chance you'd be willing to write some integration tests 

@majormoses certainly. 

The next couple of weeks are pretty busy but I'd be happy to take a stab if someone else doesn't get to it first.

**Comment by majormoses** [comment]
@phumpal I opened #43 which lays the groundwork for testing but is a bit rough. I think it is a decent starting place though. At the moment I am only testing PG 10 and hopefully we can add testing both in a matrix style for each version.

**Comment by edevreede** [comment]
Works fine now, thanks! I will not have time for the integration tests soon though.

```
root@fe962bdcb210:/docker/development# /opt/sensu/embedded/bin/gem list sensu-plugins-postgres       

*** LOCAL GEMS ***

sensu-plugins-postgres (1.4.4)
root@fe962bdcb210:/docker/development# sudo -u sensu /opt/sensu/embedded/bin/check-postgres-alive.rb                                                        
CheckPostgres OK: Server version: {"version"=>"PostgreSQL 9.6.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18) 6.3.0 20170516, 64-bit"}
root@fe962bdcb210:/docker/development# sudo -u sensu /opt/sensu/embedded/bin/check-postgres-replication.rb  --master-host 172.17.0.2 --slave-host 172.17.0.3
CheckPostgresReplicationStatus OK: replication delayed by 0.0MB :: master:0/3000060 slave:0/3000060 m_segbytes:16777216
root@fe962bdcb210:/docker/development# 

```

**Comment by majormoses** [comment]
Awesome Thanks @phumpal for fixing this up. We can make small steps towards more testing over time. I can help laying down the framework but ultimately I don't have the time to write integration tests for ~200 plugins by myself in my "free time" so it will need to be a community effort.

**Comment by opusmagnum** [comment]
I have removed function aliases, which were created as a workaround, and tested version 1.4.4 of the plugin with PostgreSQL 10.0. It works fine. 
@edevreede tested it already with PostgreSQL 9.6.4. This issue can be closed. Thanks to all participated!

**Comment by Viralshah009** [comment]
Upgrading the servers to postgres 10 breaks datadog with this error. I raised this issue with the datadog team and they provided the following workaround that worked for me. I hope it does for you guys too. Run the following as a root user on your Linux terminal:

```
wget https://gist.githubusercontent.com/dixonscottr/98c9321659027e92bd23d7cf44b2cd4a/raw/1c2dd43f45a944a23453fca9072041be530ac5cc/postgres.py

sudo mv -b postgres.py /opt/datadog-agent/agent/checks.d/postgres.py

sudo service datadog-agent restart
```

You can restore the original version of this integration with:

```
sudo mv /opt/datadog-agent/agent/checks.d/postgres.py{~,}

sudo service datadog-agent restart
```

**Comment by majormoses** [comment]
@Viralshah009 which scripts are breaking? Please open up a new issue with the information so we can track and understand the changes that needed to be made.
