### ISSUE TITLE
check-postgres-replication fails on version check with some build formats

### ISSUE THREAD

**Issue by jfineberg** [sensu-plugins/sensu-plugins-postgres#50]
Seems like the Ubuntu build of PostgreSQL that I got has an unusual version string when performing `SELECT current_setting('server_version')` and the check script returns this error:

> Check failed to run: Malformed version number string 10.3 (Ubuntu 10.3-1.pgdg16.04+1), ["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:208:in `initialize'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:199:in `new'", "/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:199:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-1.4.5/bin/check-postgres-replication.rb:109:in `check_vsn'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-postgres-1.4.5/bin/check-postgres-replication.rb:125:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]

**Comment by jfineberg** [comment]
#51 Should address this issue and also be backwards-compatible with older versions of Postgres or builds without the build version.

**Comment by majormoses** [comment]
closed via #51 

released: https://rubygems.org/gems/sensu-plugins-postgres/versions/1.4.6
